name: ZAP API Security Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ZAP API scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw owasp/zap2docker-weekly zap-api-scan.py \
            -t /zap/wrk/openapi.json \
            -f openapi \
            -r zap-report-$(date -u +'%Y%m%d').html \
            -J zap-report.json

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          path: |
            zap-report-*.html
            zap-report.json
