name: ZAP API Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run ZAP API Scan
      run: |
        docker run --rm -v $(pwd):/zap/wrk zaproxy/zap-stable \
          python3 /zap/zap-api-scan.py \
            -t /zap/wrk/openapi.json \
            -f openapi \
            -J /zap/wrk/dast-report.json \
            -r /zap/wrk/dast-report.html \
            -d -I -S \
            -z "-config api.disablekey=true"

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v3
      with:
        name: zap-reports
        path: |
          dast-report.json
          dast-report.html
